### ISSUE TITLE
Using with partials

### ISSUE THREAD

**Issue by virajsoni06** [woodyrew/metalsmith-json-to-files#1]
HI @woodyrew, thanks for the awesome plugin. I have integrated in one o my projects. However one major problem I'm facing is rendering custom metadata in Handlebars partials.

Could you please help me out here?

Thanks

**Comment by woodyrew** [comment]
Hi @virajsoni06, could you give me an example of what you're trying to achieve?

**Comment by woodyrew** [comment]
Closing due to age. If this is still a problem, get in touch.
